import os

DOXYFILE = 'Doxyfile-mcss-master'

MAIN_PROJECT_URL = './index.html'
SHOW_UNDOCUMENTED = True


FINE_PRINT = """<p>robometry documentation. Licensed under the BSD 3-Clause "New" or "Revised" License. Project maintained by the <a href="https://www.iit.it/web/icub-tech">iCub Tech department</a>. Contact the team via <a href="https://github.com/robotology/robometry/issues/new">GitHub</a>.<br />Generated by <a href="https://doxygen.org/">Doxygen</a> {doxygen_version} and <a href="https://mcss.mosra.cz/">m.css</a>."""


versions = [('<a href=\"./' + path + '/index.html\">' + path + '</a>', ) for path in next(os.walk('site'))[1] if path != 'xml']

versions.insert(0, ('<a href=\"./index.html\">Master</a>', ))

LINKS_NAVBAR1 = [
    ('Pages', 'pages', []),
    ('Classes', 'annotated', []),
    ('Files', 'files', []),
]
LINKS_NAVBAR2 = [
    ('Versions', 'pages', versions),
    ("Contacts", 'pages', [
        ("<a href=\"https://github.com/robotology/robometry\">GitHub</a>", ),
        ("<a href=\"https://www.iit.it/web/icub-tech/\">Lab website</a>", ),
    ]),
]
